export const ERROR_CODES = {
  EMPTY_INPUT: "EMPTY_INPUT",
  INPUT_TOO_LARGE: "INPUT_TOO_LARGE",
  UNSUPPORTED_MEDIA_TYPE: "UNSUPPORTED_MEDIA_TYPE",
  INVALID_EXTENSION: "INVALID_EXTENSION",
  MISMATCHED_TYPE: "MISMATCHED_TYPE",
  ENCODING_INVALID: "ENCODING_INVALID",
  NORMALIZATION_FAILED: "NORMALIZATION_FAILED",
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
  SAMPLE_NOT_FOUND: "SAMPLE_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND",
  EVALUATION_FAILED: "EVALUATION_FAILED",
  EVALUATION_TIMEOUT: "EVALUATION_TIMEOUT",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED",
  EXPORT_FAILED: "EXPORT_FAILED",
  INTERNAL: "INTERNAL"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
